### PR TITLE
chore: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks! Although I have some qualms about this change. This forces a global install of the latest version of npm. What if users do not want to upgrade their `npm`? This seems outside the purview of `ncu`.

**Comment by DanielRuf** [comment]
> Thanks! Although I have some qualms about this change. This forces a global install of the latest version of npm. What if users do not want to upgrade their npm? This seems outside the purview of ncu

This just affects GitLab, not normal users.

**Comment by DanielRuf** [comment]
> Thanks! Although I have some qualms about this change. This forces a global install of the latest version of npm. What if users do not want to upgrade their npm? This seems outside the purview of ncu

This just affects Travis CI, not normal users.

**Comment by raineorshine** [comment]
Ah, my bad. Should have noticed it was the .travis.yml file.

I am still confused about the purpose and safety of this change. If there is a before_install script that updates npm to latest, doesn't that defeat the purpose of travis testing across multiple versions of node and npm?

**Comment by raineorshine** [comment]
Closing but happy to reopen if a reason is provided! Thanks!

**Pull request closed without merging**
