### PR TITLE
[WIP] Use global-npm instead of local npm dep

### LINKED ISSUE #350: Deprecate npm commands api
We should not use `npm.commands` anywhere (https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L21). Instead we should invoke npm as a child_process and parse the results, as done here: https://github.com/tjunnone/npm-check-updates/blob/master/lib/package-managers/npm.js#L94.

This ensures that npm-check-updates is using the user's installed npm version rather than the one that ships with npm-check-updates.

### PR DESCRIPTION
**Pull request by karanjthakkar**
~Waiting on https://github.com/maxleiko/npmi/issues/9 but this PR attempts to use the global npm version instead of the local one.~ Updated npmi to `4.0.0`

@raineorshine Do you think this should fix #350 or is there an even stronger reason to not use `npm.commands` and parse on our end?

### CODE REVIEW

**Comment by karanjthakkar** [comment]
Yikes. I just realised I should've created the PR against `v3`. Right?

**Comment by karanjthakkar** [comment]
I've been very out of touch with the project. Just saw the commit you made in the v3 branch https://github.com/tjunnone/npm-check-updates/commit/c0bd8b72fa353d6471f8ccb400d6e4d79b1568d5 Does this PR even make sense after that? 🙈

**Comment by raineorshine** [comment]
I'm sorry, I'm swamped with work right now. I doubt I will have time in the near future to look into this.

**Comment by nickmccurdy** [comment]
@karanjthakkar This looks great, especially since Synk is reporting a [vulnerability](https://snyk.io/test/npm/npm-check-updates/) for `ncu`'s current verrsion of npm which seems to be fixed in newer versions of npm. If you two are okay with it I think it would be a good idea to release this as a minor or patch release of 2, time permitting.

@raineorshine Is there anything we can do to help with v3 or maintenance in general?

**Comment by raineorshine** [comment]
@nickmccurdy Yes, I'm at a complete standstill on ncu development due to other commitments. If you guys can put together a good PR to move things forward, I would be happy to review and make a release.

**Comment by raineorshine** [comment]
@karanjthakkar @nickmccurdy Do you have any availability coming up? I'd love to get `v3` out there.

**Comment by karanjthakkar** [comment]
@raineorshine Absolutely. I'm pretty free this weekend so if you have a plan on what needs to be done, I'm happy to help out.

**Comment by raineorshine** [comment]
In regard to the to-date implementation of this PR, please note that `global-npm` is not a valid approach since it uses npm as a module. We have to interact with it as a cli. See https://github.com/npm/npm/issues/8283#issuecomment-103718763. It may be possible to use [`npm-registry-client`](https://github.com/npm/npm-registry-client/) but it would need to be investigated further.

**Comment by raineorshine** [comment]
We need to rebase `v3` and make sure it is working properly. I did a lot in https://github.com/tjunnone/npm-check-updates/commit/c0bd8b72fa353d6471f8ccb400d6e4d79b1568d5 but don't recall whether it was complete.

**Comment by karanjthakkar** [comment]
@raineorshine iiuc, https://github.com/npm/npm/issues/8283#issuecomment-103718763 is already resolved in https://github.com/tjunnone/npm-check-updates/commit/c0bd8b72fa353d6471f8ccb400d6e4d79b1568d5 right?

Things to do next:
- rebase v3 on the latest master 
- check if implementation for removing `npm.commands` is complete. Is there a way to verify this? If all tests pass, should this be assumed to be working?

**Comment by raineorshine** [comment]
@karanjthakkar Is *should* be resolved, but again this needs to be confirmed. ncu has great unit test coverage, so the tests just need to pass.

Correction: I'm used to rebasing local branches, but we don't want to alter the history of a published branch, so we should merge master into v3, not rebase.

**Comment by karanjthakkar** [comment]
@raineorshine Gotcha. So if I create a branch off of `v3` and merge master into it and if the CI passes, we should be fine?

**Comment by raineorshine** [comment]
@karanjthakkar Yes. hard part may be resolving merge conflicts however!

**Comment by karanjthakkar** [comment]
@raineorshine I could give it a shot. What timezone are you in? If its too difficult for me then maybe we could pair up and do it together when you find the time?

**Comment by raineorshine** [comment]
I'm in MST. If you are running into walls, maybe I can complete the merge
so that you have a clear path to implement the other v3 features. Reach out
on Gitter if you want to chat more!

**Comment by raineorshine** [comment]
Closing, as this has been fixed in the v3 branch.

**Pull request closed without merging**
