### PR TITLE
Don't say "latest version" and "ncu -u" when nothing should be upgraded

### LINKED ISSUE #575: Question: When choosing no should it say "All dependencies match the latest package versions :)"
- [x] I have read the list of [known issues](https://github.com/tjunnone/npm-check-updates#known-issues) before filing this issue.
- [x] I have searched for [similiar issues](https://github.com/tjunnone/npm-check-updates/issues) before filing this issue.

* node version: v12.9.1
* npm version: 6.11.3
* npm-check-updates version: 3.1.21

---------------------------

When running ncu and choosing `no` on all proposed updates, it reports "All dependencies match the latest package versions :)"

Is this intended or is it a bug?
Saying no means all dependencies match the _desired_ versions yes but not the _latest_, as there are obviously newer versions reported. 🤔 

Screenshot 2019-09-05 at 11 24 33

What do you think?

### PR DESCRIPTION
**Pull request by Primajin**
Closes #575

Before:
Bildschirmfoto 2019-09-07 um 14 54 39

After:
Bildschirmfoto 2019-09-07 um 14 54 26

Also removes some duplicated code and updates some JSDoc.

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks!

**Comment by raineorshine** [comment]
Published in `v3.1.22`

**Comment by Primajin** [comment]
I seem to have added a regression 😱 
Now `-g` doesn't show all dependencies up to date.
Screenshot 2019-09-10 at 17 36 19

**Comment by raineorshine** [comment]
@Primajin Oops! Can you work on a fix?

**Comment by Primajin** [comment]
I can see if I find it quick but I'm out on a long vacation from Thursday. Fingers crossed 🤞🏻

**Comment by Primajin** [comment]
This could be it 🤞🏻: #579

**Pull request merged**
