### PR TITLE
Fix --silent option regression

### PR DESCRIPTION
**Pull request by karanjthakkar**
Possible fix for #317. 

Two points I want to ask:

1. The current fix will override `loglevel` option when the `silent` option is provided. I think this is how it should work. But not sure if the `!options.loglevel` check was given there for a specific reason. What do you think?

2. How do we test if the silent option is set correctly? Just to make sure this doesn't break in the future again.

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks for working on this!!!

1. I agree, `--silent` should take precedence.

2. https://github.com/tjunnone/npm-check-updates/blob/master/test/test-ncu.js#L87

**Comment by karanjthakkar** [comment]
Added a unit test to check that `--silent` works :)

**Comment by raineorshine** [comment]
Looks good! Just remove the `in-progress` label when you feel it's ready to merge.

**Comment by karanjthakkar** [comment]
Done! 😎

**Pull request merged**
