### PR TITLE
[V3] Remove npm dependency

### PR DESCRIPTION
**Pull request by bastienmoulia**
Linked to https://github.com/tjunnone/npm-check-updates/issues/350

### CODE REVIEW

**Comment by yvele** [comment]
Yep, having a dependency to `npm-check-updates` makes having his `npm` v3 in bin, and makes `npm scripts` using it instead of the global `npm`.. Resulting in lot of bugs

**Comment by vdh** [comment]
It looks like `npmi` will also need to be removed? Otherwise its dependency to `npm` will still install the second copy.

**Comment by raineorshine** [comment]
Yes, npmi needs to be removed as well.

**Comment by raineorshine** [comment]
Closing as the local npm has been removed in the soon-to-be-released [v3](https://github.com/tjunnone/npm-check-updates/issues/471).

**Pull request closed without merging**
