### PR TITLE
chore: test Node.js 6, 8 and 10

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by DanielRuf** [comment]
Seems we found actual failures on Node.js 8 and 10.

**Comment by raineorshine** [comment]
This will be done in ncu `v3` since it is a breaking change.

**Comment by DanielRuf** [comment]
Ok, but does this address the compatibility with Node.js 8 and 10 (where the tests fail)?

**Comment by raineorshine** [comment]
@DanielRuf A fix is needed for that test that is failing. I added #448 for tracking purposes.

**Comment by raineorshine** [comment]
All tests are passing on the `v3` branch now for node 8, 10, and 11.

https://travis-ci.org/tjunnone/npm-check-updates/builds/482186035

**Pull request closed without merging**
