### PR TITLE
Add progress bar

### PR DESCRIPTION
**Pull request by stoically**
Simple progress bar using [`progress`](https://github.com/visionmedia/node-progress)

Rebased on top of #497 (because of package(-lock).json)

### CODE REVIEW

**Comment by petercunha** [comment]
Long overdue! Well done, hopefully this gets merged.

**Comment by raineorshine** [comment]
Looks good once #497 is done! Thank you!

**Comment by petercunha** [comment]
Nice! Thanks for merging

**Comment by raineorshine** [comment]
Published in v3.0.5

**Pull request merged**
