### PR TITLE
Added tests for invalid and wildCard ranges with --newest option

### PR DESCRIPTION
**Pull request by webdevium**
Fixed successful work in case of incorrect ranges.
For omitting errors like #608

### CODE REVIEW

**Comment by raineorshine** [comment]
Thank you!

**Comment by webdevium** [comment]
@raineorshine Have you thought about improving branch coverage?

**Comment by raineorshine** [comment]
You mean like unit tests for other branches? Sorry I'm not familiar. Can you explain a bit?

**Comment by webdevium** [comment]
No, in **master** branch.
If you look at test coverage, you will see that not all conditions are covered in `if/else/ternary operator` statements. It is called branch coverage.

**Comment by raineorshine** [comment]
Ah! That kind of branch :). Yes, we could really use better coverage!

**Pull request merged**
