### PR TITLE
Added support for .ncurc config files using rc-config-loader

### PR DESCRIPTION
**Pull request by cavinsmith**
* Added  rc-config-loader@2.0.1 (https://github.com/azu/rc-config-loader)

* Reading `.ncurc{.json,.yml,.js}` as documented for rc-config-loader

* Combining parameters read from rc with argv putting them in the beginning of user arguments list so custom arguments will override provided in rc

* P.S. Added `.DS_store` to `.gitignore`

### CODE REVIEW

**Comment by raineorshine** [comment]
Thanks! Can you write a unit test to confirm this functionality? It can write a temp file as seen here:
https://github.com/tjunnone/npm-check-updates/blob/master/test/test-ncu.js#L170

Testing that it reads a single config value is sufficient for our purposes. Thanks!

**Comment by raineorshine** [comment]
Oh, and please add a sentence to the README under `Options` that describes this functionality! Thanks!

**Comment by cavinsmith** [comment]
@raineorshine 

* Added `configFilePath` and `configFileName` to allow custom config paths and files and to provide tests

* Added tests for: loading by path, loading by name, overriding config file options with arguments

* Added options info and configuration description to README.MD

**Comment by raineorshine** [comment]
Beautiful! Thanks for your work!

Published in `v2.14.0`

**Pull request merged**
